# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
#    ignore:
#      - dependency-name: "*"
#        # patch and minor updates don't matter for libraries
#        # remove this ignore rule if your package has binaries
#        update-types:
#          - "version-update:semver-patch"
#          - "version-update:semver-minor"
